# SPDX-FileCopyrightText: 2019 Authelia
#
# SPDX-License-Identifier: Apache-2.0

---
version: '3'
networks:
  authelianet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.240.0/24
...
